name: tests
on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
 hello:
   if: ${{ github.event.issue.pull_request && github.event.comment.body == '/hello'}}    # check if the comments come from pull request, exclude those from issue.
   runs-on: [ubuntu-latest]
   steps:
      - name: test
        run: |
           echo Hello!