name: release

on:
  push:
    tags:
      - 'v*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set release variable 
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Get release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo MESSAGE=`hub release show ${{ env.RELEASE_VERSION }}` >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          repository: mjudeikis/vuepress-example
          #token: ${{ secrets.my_pat }}
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN_RELEASE }}
        run: hub release create ${{ env.RELEASE_VERSION }} -m "${{ env.MESSAGE }}"


