name: unit-tests

on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
  unit:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/unit'}} 
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Checkout Pull Request
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Diff revision
        id: coverage
        shell: bash
        run: |
          make test-unit-ci

          cov=$(make test-unit-coverage)
          echo $cov

          echo "::set-output name=coverage::$cov"

      - name: 'Comment PR'
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: 'Hello world ! 👋' });