name: unit-tests

on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
  unit:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/unit'}} 
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Checkout Pull Request
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Diff revision
        id: coverage
        shell: bash
        run: |
          make test-unit-ci
          make test-unit-coverage

          coverage=$(make test-unit-coverage)

          echo "::set-output name=coverage::$coverage"

      - name: Create pull-request against master
        uses: octokit/request-action@v2.x
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/:repository/pulls
          repository: ${{ github.repository }}
          title: Merge ght/master into master
          head: ght/master
          base: master
          body: |
            Coverage: ${{ steps.coverage.outputs.coverage }}